name = "blang"
license = "MIT"
description = "blang.io default theme"
min_version = 0.14

[author]
  name = "blang"
  homepage = "//github.com/blang"

# Ported original from https://bootswatch.com/united/
[original]
    author =  "thomaspark"
    license = "MIT"
    repo = "https://github.com/thomaspark/bootswatch/"